---
  extends:
    - airbnb-base
  root: true
  parser: "babel-eslint"
  env:
    es6: true
    node: true
  rules:
    camelcase:
      - 0
      -
        allow:
          - calc_time
    newline-per-chained-call:
      - 0
    no-underscore-dangle:
      - 0
    no-bitwise:
      - 2
      -
        allow:
          - "^"

  overrides:
    -
      files:
        - test.js
      rules:
        import/no-extraneous-dependencies:
          - 0
